/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gologolo;

/**
 *
 * @author jasoncao
 */
public enum goLogoLoPropertyType {
    //background pane
    LOGO_PANE,
    //editing, middle pane
    LOGO_EDIT_PANE,
    //LEFT PANE WITH CHART AND ICONS ON BOTTOM
     LOGO_CHART_PANE,
     LOGO_TABLE_VIEW,
     GOLOGOLO_NAME_COLUMN,
     GOLOGOLO_ORDER_COLUMN,
     GOLOGOLO_TYPE_COLUMN,
     LOGO_TABLE_BUTTONS_PANE,
     MOVE_UP_BUTTON,
     MOVE_DOWN_BUTTON,
     RENAME_BUTTON,
     LOGO_RIGHT_PANE,
   LOGO_COMPONENTS_BUTTONS_PANE,
   ADD_TEXT_BUTTON,
   DELETE_BUTTON,
   ADD_IMAGE_BUTTON,
   ADD_CIRCLE_BUTTON,
   ADD_TRIANGLE_BUTTON,
   ADD_RECTANGLE_BUTTON,
   LOGO_FONT_BUTTONS_PANE,
   BOLD_BUTTON,
   ITALICIZE_BUTTON,
   INCREASE_TEXT_BUTTON, 
   DECREASE_TEXT_BUTTON,
   UNDERLINE_BUTTON,
   LOGO_FONT_COMBO_BOX,
   LOGO_FONT_SIZE_COMBO_BOX,
   LOGO_BORDER_CONTROL_PANE,
   LOGO_BORDER_COLOR_COMBO_BOX,
   LOGO_BORDER_THICKNESS_SLIDER,
   LOGO_BORDER_RAIDIUS_SLIDER,
   GOLOGOLO_BORDER_THICKNESS_LABEL,
   DEFAULT_FONT,
   FONT_OPTIONS,
   DEFAULT_FONT_SIZE,
   FONT_SIZE_OPTIONS,
   BORDER_COLOR_OPTIONS,
   DEFAULT_BORDER_COLOR,
   GOLOGOLO_BORDER_COLOR_LABEL,
   GOLOGOLO_BORDER_RADIUS_LABEL,
   COLOR_PICKER,
   
}
